#!/bin/sh

blue="\e[34m"
reset="\e[0m"

export PATH=./bin:$PATH


function run_tests {
    for test_script in tests/*.sh; do
        printf "${blue}-- $test_script${reset}\n"
        bats --tap $test_script
        echo ''
    done
}

function download_sample_files {
    # download a tiny sample video
    [ ! -f tests/source/tiny.mp4 ] \
        && youtube-dl \
                -f 18 \
                -o tests/source/tiny.mp4 \
                H8XaHC4ilts

    # smaller AC3 source file
    # found via http://www.digital-digest.com/movies/movie_index.php?type=dolby
    if [ ! -f tests/source/720p-ac3.vob ]; then
        curl -C- -O http://downloads.dvdloc8.com/trailers/dolbydts/dolbycanyon.zip
        unzip dolbycanyon.zip
        mv dolbycanyon.vob tests/source/720p-ac3.vob
        rm dolbycanyon.zip readme.txt
    fi

    # DTS source
    # found via http://www.digital-digest.com/movies/movie_index.php?type=dolby
    if [ ! -f tests/source/sd-dts.vob ]; then
        curl -C- -O http://downloads.dvdloc8.com/trailers/dolbydts/dtspiano.zip
        unzip dtspiano.zip
        mv dtspiano.vob tests/source/sd-dts.vob
        rm dtspiano.zip readme.txt
    fi

    # AAC source
    if [ ! -f tests/source/aac.mp4 ]; then
        curl -C- -L -o tests/source/aac.mp4 \
            https://archive.org/download/5.1SurroundSoundTestFilesVariousFormatsAACAC3MP4DTSWAV/Splash.mp4
    fi

    # MP3 source
    # found via http://www.divx.com/en/devices/profiles/video
    [ ! -f tests/source/mp3.divx ] \
        && curl -o tests/source/mp3.divx \
                http://trailers.divx.com/divx_prod/profiles/Helicopter_DivXHT_ASP.divx
}

function download_posters {
    [ ! -f tests/source/tv.jpg ] \
        && curl -o tests/source/tv.jpg \
            http://is1.mzstatic.com/image/thumb/Music/v4/8c/cc/4c/8ccc4c87-878a-77d8-c358-e036c8c25b7b/source/600x600bb.jpg
    [ ! -f tests/source/movie.jpg ] \
        && curl -o tests/source/movie.jpg \
            http://is2.mzstatic.com/image/thumb/Video/v4/f6/72/6e/f6726e35-72e3-9cab-d435-3bec128c5ed4/source/600x600bb.jpg
}

function copy_files_to_specific_locations {
    mkdir -p "tests/process/House - 1x01 - Pilot"
    cp tests/source/720p-ac3.vob "tests/process/House - 1x01 - Pilot/house.vob"
    cp tests/source/tv.jpg       "tests/process/House - 1x01 - Pilot/poster.jpg"
}


download_sample_files
download_posters
copy_files_to_specific_locations
run_tests
