#!/bin/sh

blue="\e[34m"
reset="\e[0m"

export PATH=./bin:$PATH


function run_tests {
    for test_script in tests/*.sh; do
        printf "${blue}-- $test_script${reset}\n"
        bats --tap $test_script
        echo ''
    done
}

function download_sample_files {
    # download a tiny sample video
    [ ! -f tests/source/tiny.mp4 ] \
        && youtube-dl \
                -f 18 \
                -o tests/source/tiny.mp4 \
                H8XaHC4ilts

    # smaller AC3 source file
    # found via http://www.digital-digest.com/movies/movie_index.php?type=dolby
    if [ ! -f tests/source/720p-ac3.vob ]; then
        curl -C- -O http://downloads.dvdloc8.com/trailers/dolbydts/dolbycanyon.zip
        unzip dolbycanyon.zip
        mv dolbycanyon.vob tests/source/720p-ac3.vob
        rm dolbycanyon.zip readme.txt
    fi
}

function download_posters {
    [ ! -f tests/source/tv.jpg ] \
        && curl -o tests/source/tv.jpg \
            http://is1.mzstatic.com/image/thumb/Music/v4/8c/cc/4c/8ccc4c87-878a-77d8-c358-e036c8c25b7b/source/600x600bb.jpg
    [ ! -f tests/source/movie.jpg ] \
        && curl -o tests/source/movie.jpg \
            http://is2.mzstatic.com/image/thumb/Video/v4/f6/72/6e/f6726e35-72e3-9cab-d435-3bec128c5ed4/source/600x600bb.jpg
}


download_sample_files
download_posters
run_tests
